#!/usr/bin/env bash

alacritty_path=~/.config/alacritty
alacritty_colors="$alacritty_path"/colors
alacritty_target="$alacritty_path"/colors.toml

use_dmenu() {
  local current_theme
  if [[ -f "$alacritty_target" ]]; then
    current_theme="$(sed -n '$p' $alacritty_target | cut -d'#' -f2 | cut -d'.' -f1)"
  fi
  dmenu -i -l 20 -p "Select alacritty ($current_theme):"
}

select_theme() {
  find "$alacritty_colors" -type f -printf "%f\n" |
    sort -d -f |
    use_dmenu
}

use_this="$(select_theme)"
[[ -n "$use_this" ]] &&
  cat "$alacritty_colors"/"$use_this" >"$alacritty_target" &&
  echo "#$use_this" >>"$alacritty_target"
