#!/bin/sh
#
# Old name: tat
# Attach or create a tmux session having the same name as current directory.
# --> Currently aliased to "a"

path_name="$(basename "$PWD" | tr . -)"
session_name=${1-$path_name}

not_in_tmux() {
	[ -z "$TMUX" ]
}

session_exists() {
	tmux list-sessions | sed -E 's/:.*$//' | grep -q "^$session_name$"
}

create_detached_session() {
	(TMUX='' tmux new-session -Ad -s "$session_name")
}

create_if_needed_and_attach() {
	if not_in_tmux; then
		# The -A flag makes new-session behave like attach-session if session-name already exists;
		# in this case, -D behaves like -d to attach-session, and -X behaves like -x to attach-session.
		tmux new-session -As "$session_name"
	else
		if ! session_exists; then
			create_detached_session
		fi
		tmux switch-client -t "$session_name"
	fi
}

create_if_needed_and_attach
