#!/usr/bin/env bash

_find() {
  find ~/.config/tmuxp -name "*.yml"
  find \
    ~/projects/plugins \
    ~/projects/rust \
    ~/projects/docs \
    ~/localbuilds \
    ~/.config \
    ~/bin \
    ~/git \
    ~/inspiration/vim \
    -mindepth 1 -maxdepth 1 -type d
}

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(_find | fzf --reverse)
fi

if [[ -z $selected ]]; then
  exit 0
fi

# if ! [[ -d $selected ]]; then
if [[ $(echo $selected | grep -c yml) > 0 ]]; then
  tmuxp load $selected -y
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# -c is start directory
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s "$selected_name" -c "$selected"
  exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
  # The new session is attached to the current terminal unless -d is given
  tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t "$selected_name"
